### ISSUE TITLE
Game crashes within seconds after picking up the rifle

### ISSUE THREAD

**Issue by napo1emon** [andtheherois/3DSS-IWP-SV98-Port#2]
Playing Stalker GAMMA. Those are the last few mods in my load order:

Mark Switch v12.1
Meowie's scope textures v2.6
GAMMA 3D Shader Based Scopes
IWP.SV98.Port-2.2

After picking up the SV98 from a container the came crashes, sometimes right away, sometimes after 20 seconds. Bottom of my log looks like this:

`[error][       8] : Not enough memory resources are available to process this command.`

`at address 0x00000001401E4651`
`refCount:pBaseZB 1`
`refCount:pBaseRT 1`

Error message:
![error](https://github.com/user-attachments/assets/abc0fdf4-f87a-4da8-9475-762c0eafb1c3)

**Comment by napo1emon** [comment]
This doesn't happen if I spawn a new rifle with debug menu. So problem solved I guess.

**Comment by andtheherois** [comment]
I think I may know why this is. I'll be upload a fix soon.

**Comment by napo1emon** [comment]
The world model issue is gone, but sadly, v2.3 still crashes the game. Bottom of the log:

`[error][       8] : Not enough memory resources are available to process this command.`

`at address 0x00000001401E8401`
`refCount:pBaseZB 1`
`refCount:pBaseRT 1`

I have one SV98 stashed in a container, and the crash happens within a minute of taking it out. One can assume that every pre-existing instance of this gun is affected. So if there's an NPC carrying it in my save, and I take it from them, this will probably happen again. But when I spawn a new SV98, the game doesn't crash.

I want you to know that it is not a big issue for me, and I don't want to come out as someone nagging you to "fix my game". But the bug is there if you want to take care of it. ;)

**Comment by napo1emon** [comment]
I tested a bit more:

1. deactivated your mod,
2. loaded a save and moved the SV98 from the container to my inventory and saved the game,
3. activated your mod again,
4. loaded a save with the rifle in hands,
5. no crash.

I guess the problem was connected to the fact that the container was a weapon rack that displays world models. A very specific bug scenario, but easily fixed by the player.
