### ISSUE TITLE
wpn_sv98_custom problems

### ISSUE THREAD

**Issue by napo1emon** [andtheherois/3DSS-IWP-SV98-Port#3]
This happens on 3DSS 2.11:
the 1p59 scope works fine on the wpn_sv98, but the other scope that is on the wpn_sv98_custom is all black.
The last time I had a similar issue it was because of outdated 3DSS files [https://github.com/andtheherois/3DSS-For-BAS22/issues/2]

After installing 3DSS 2.12 and deleting shader cache the game crashes when trying to equip wpn_sv98_custom.

Bottom of the log:

```
#actor took wpn_sv98_custom
stack trace:

SymInit: Symbol-SearchPath: '.;E:\StalkerAnomaly\bin;E:\StalkerAnomaly\bin;C:\Windows;C:\Windows\system32;', symOptions: 530, UserName: 'lemon'
OS-Version: 6.2.9200 () 0x100-0x1
E:\StalkerAnomaly\bin\AnomalyDX11.exe:AnomalyDX11.exe (0000000140000000), size: 18341888 (result: 0), SymType: '-exported-', PDB: 'E:\StalkerAnomaly\bin\AnomalyDX11.exe'
 
[error][       8] : Not enough memory resources are available to process this command.

at address 0x00000001401E9E74
refCount:pBaseZB 1
refCount:pBaseRT 1
```

**Comment by andtheherois** [comment]
nothing useful in that log

**Comment by napo1emon** [comment]
I tried again and now the game doesn't crash when equipping sv98_custom. Huh. I'm getting a fair number of random crashes lately.
Anyway, the black/red scope is on both versions of 3DSS.
